name: AlphaScout CI
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r CI/requirements-dev.txt
      - name: Ruff lint
        run: ruff check .
      - name: Black (check only)
        run: black --check .
      - name: Mypy
        run: mypy .
      - name: Pytest with coverage
        run: coverage run -m pytest && coverage report -m
      - name: Upload coverage XML
        run: coverage xml
      - name: Store coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

