name: pre-commit
on:
  pull_request:
  push:
    branches: [ main ]  # change if your default branch is not 'main'

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: CI/requirements-dev.txt
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
